### ISSUE TITLE
Proposal: Monadic operators

### ISSUE THREAD

**Issue by ncthbrt** [aantron/repromise#11]
Repromise introduces monadic behaviour to promises. 

As a convenience, it would be nice to have a `map` operator with the signature `('a => 'b, Repromise.t('a)) => Repromise('b)`. This makes Repromise have semantics which are as convenient as javascript's automatic wrapping (in js `Promise.resolve(4).then(a => a * 2)` returns a promise). If this were to be adopted, it would also be wise to add the function `flatMap` which would simply be an alias for `then_`.

**Comment by aantron** [comment]
Definitely agreed on `map`. Indeed, it was already planned, so if you want to add it sooner, I will happily merge it.

I hesitate to add an alias. It would be easy to maintain, of course. But, each additional API carries learning, memory, and decision-making overhead for users, even if only it is only an alias. What's the rationale for adding `flatMap`?

My thinking is that it's better to have one function called `then_`/`flatMap`/`bind`/whatever, and the name `then_` is best because of familiarity to the greatest number of users. It is also the most descriptive one from this list.

The kinds of rationales for adding an alias I can think of would be if it's really convenient to pass module `Repromise` directly to a functor without having to wrap it to translate function names, and some functor expects `flatMap`. But I don't think anybody is using or will use Repromise that way.

**Comment by ncthbrt** [comment]
Main reason for aliasing flatMap would be if Observables were to be which included which could also include `map/flatMap`
