### ISSUE TITLE
Wrap lwt and Async?

### ISSUE THREAD

**Issue by bobpoekert** [aantron/repromise#19]
Most native reason code is going to be wrapping opam libraries for doing things like http requests and database queries, and those native libraries are going to be using either lwt or Async. It would be great if you could, for example, have an http client library that used either bs-fetch or cohttp under the hood, depending on the platform, and exposed a common api for both. Is this something that it would make sense for repromise to do, or would it make more sense for that to be a separate library?

**Comment by kennetpostigo** [comment]
Hey @bobpoekert  @aantron !

I'm working on these at the moment all built with reason
- Http Module
- Cross-Platform `fetch` to make network requests.

At the moment these use `lwt` under the hood, but if all goes well, @aantron and I can converge on using Repromise promises. Or if repromise becomes lwt 5.0/6.0 i'd just keep depending on lwt and update w/e needs to be updated.

**Comment by bobpoekert** [comment]
@kennetpostigo How are you implementing your cross-platform fetch? Do you have converters/wrappers from bucklescript promises to lwt promises and a stripped-down version of lwt that runs on bucklescript? Or do you have some other promise type that wraps both?

**Comment by kennetpostigo** [comment]
js side uses what bucklescript exposes, but native side uses unix pipes

**Comment by bobpoekert** [comment]
@kennetpostigo but what's the common abstraction that cross-platform consumer code uses?

**Comment by aantron** [comment]
@kennetpostigo @bobpoekert is asking, I believe, what is the underlying synchronization primitive (e.g. promise implementation) that is being compiled to native and js, that lwt-node would build its isomorphic API over.

The answer to that is, I think, that lwt-node is not there yet.

Repromise has isomorphic native/js promises, but it is not yet compatible with Lwt (or Async).

lwt-node uses Lwt right now, and so presumably is native-only for the time being.

**Comment by kennetpostigo** [comment]
oh right, like I said before, right now for js we're using what bucklescript offers and for native we are using unix pipes.

**Comment by aantron** [comment]
There is now a super basic POC of Repromise/Lwt interop [here](https://github.com/aantron/repromise_lwt#readme).

Basically, Lwt_unix (the I/O part of Lwt) drives the process I/O loop, and calls into Repromise when I/O resolves a promise and triggers a callback.

There are also two functions for converting Lwt and Repromise promises between each other.

The test case has a [simple wrapper](https://github.com/aantron/repromise_lwt/blob/3172086fbbb9256ebcc80f8faaef76b51559a9a7/test/test.re#L2) around `Lwt_unix.sleep`, that turns it into a Repromise-friendly `sleep`.

**Comment by lessp** [comment]
Hey @aantron, this looks like a super-promising library, are there still plans for this?

Perhaps this would also be interesting from the previous discussion's perspective? https://github.com/anuragsoni/fetch/

**Comment by aantron** [comment]
Yep, still planning to look into this in great detail :)

From the other end, there is also https://github.com/aantron/luv, for rewriting Lwt over libuv (what's used by Node internally for I/O). That's what I've spent the most time on recently.

Most recently, though, I went on a small hiatus, but planning to come back to all this soon.

**Comment by lessp** [comment]
Oh, very interesting, there's lots of potential for making the community more approachable here! 

Thanks for all your hard work, excited to follow the progress on these! 🙏

**Comment by aantron** [comment]
I'm going to close this issue to keep the repo tidy, because progress needs to be tracked in other repos that would drive Repromise:

- [repromise_lwt](https://github.com/aantron/repromise_lwt) is a Repromise/Lwt interop demo, in which the native version of Repromise is being driven by **Lwt** (`Lwt_engine` inside `Lwt_unix`). That is, Lwt plays the role of Node.js, or the browser JS runtime.
- [**Luv**](https://github.com/aantron/luv) is a binding to libuv, the same C async I/O library that drives Node.js. It has an [example](https://github.com/aantron/luv/blob/8ee62103540425e268c6536d8c946548a9eb09ab/example/http_get_repromise/http_get_repromise.re) where native Repromise, driven by Luv, is doing an HTTP GET (low-level version, not fetch). It has another [example](https://github.com/aantron/luv/blob/master/example/interop_repromise_lwt/interop_repromise_lwt.re) of native Repromise and Lwt coexisting in one process, because both are being driven by Luv.

Even though this issue is closed, further discussion is welcome!
