### ISSUE TITLE
Coerce to JS.Promise

### ISSUE THREAD

**Issue by lpil** [aantron/repromise#25]
There are various Bucklescript libraries today that take Js.Promises are arguments (i.e. bs-express). It would be great to use Repromise with these libraries!

Would it be possible to have a coerce function that converts a Repromise promise to a Js.Promise? 

Thanks,
Louis

**Comment by aantron** [comment]
Agreed. I'll have to think about how to package these, because they need to go in the `.rei` file, but the `.rei` file is shared between JS and native, and `Js.Promise` doesn't exist on native. Might have to split the `.rei` files, so each implementation gets its own. I guess it won't be a big deal in terms of them going out of sync, because we still subject both JS and native Repromise to the same tests.

In the meantime, here is how these can be defined:

```ocaml
external fromJSPromise:
  Js.Promise.t('a) => Repromise.Rejectable.t('a, Js.Promise.error) =
  "%identity";

external toJSPromise:
  Repromise.Rejectable.t('a, _) => Js.Promise.t('a) = "%identity";
```

**Comment by aantron** [comment]
Ok, I added the functions to `master`, as `Repromise.Rejectable.fromJsPromise` and `Repromise.Rejectable.toJsPromise`.

The commit also includes tests and docs.

Thanks for prompting this :)

**Comment by lpil** [comment]
Thank you!

**Comment by aantron** [comment]
This is now in NPM in [`@aantron/repromise` 0.6.0](https://github.com/aantron/repromise/releases/tag/0.6.0). Thanks again for prompting it :)
